# Generated by Django 3.0.4 on 2020-09-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestProjectApp', '0002_auto_20200906_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='EmailID',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='LoginID',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
